<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LibUsbDotNet">
      <HintPath>LibUsbDotNet.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="libusb-1.0.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libusb-1.0.lib">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>